"use client";

import Section from "@/components/Section";
import Mermaid from "@/components/Mermaid";
import { noisyRetrieval } from "@/data/charts";

export default function RetrievalPage() {
  return (
    <main className="space-y-24 sm:space-y-32 py-10 sm:py-16">
      <Section id="embeddings" title="Noisy Retrieval and Critic Gating" subtitle="Retrieval channel and precision mechanism (paper Section 3, Fig. 2b).">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">
          <div>
            <Mermaid chart={noisyRetrieval} className="rounded-xl border border-neutral-200 dark:border-white/10 bg-neutral-50 dark:bg-neutral-900/60 p-4 overflow-x-auto" highlights={{}} descriptions={{
              "Planner query q_t": "Query generated by the Planner to retrieve relevant context from memory. Even if perfectly formed, the retrieval process introduces noise due to embedding misalignment or approximate search errors.",
              "Retrieval channel C_η": "Corruption channel parameterized by noise level η. m̃_t ~ C_η(m_t) is probabilistically correlated with the true memory item m_t. Lower η yields more accurate retrieval; higher η introduces more errors.",
              "Context m̃_t ~ C_η(m_t)": "Noisy retrieved evidence. The actual retrieved result (possibly corrupted) is probabilistically correlated with the true relevant memory entry. Models imperfect recall from approximate nearest neighbor search.",
              "Executor → a_t": "Produces candidate action a_t conditional on query q_t and retrieved context m̃_t. The candidate is then evaluated by the Critic.",
              "Critic (α, β)": "α = Pr(approve|incorrect) is the false approval rate; β = Pr(reject|correct) is the false rejection rate. PPV: P(correct|approve) = (1-β)p' / [(1-β)p' + α(1-p')]. Minimizing α and β ensures high-quality memory.",
              "PPV: P(correct|approve)": "Positive predictive value: how confident we can be that an approved candidate is actually correct. A high PPV means Critic approvals are trustworthy, controlling memory quality.",
              "Memory M_{t+1}": "Memory grows only when Critic approves. Rejected candidates leave no trace, preventing incorrect results from contaminating future reasoning steps. Mirrors spike-timing dependent plasticity (STDP).",
            }} />
            <div className="mt-2 text-xs text-neutral-600 dark:text-neutral-400"><strong>Figure 4.</strong> Noisy retrieval channel C_η and critic gating mechanism showing how retrieval probability p(η) and critic errors (α,β) determine memory precision (from paper Fig. 2b).</div>
          </div>
          <div className="space-y-4 text-neutral-700 dark:text-neutral-300 text-base/7">
            <p><strong>Noisy Channels Formalism.</strong> Both memory retrieval and candidate evaluation are imperfect—they can return wrong results or make incorrect judgments. We model these as <em>noisy channels</em> to formally reason about error propagation, connecting to information-theoretic principles.</p>
            <p><strong>Retrieval Channel.</strong> When the Planner queries memory, the Retriever may return imperfect results due to embedding misalignment or approximate search errors. The retrieved context m̃_t ~ C_η(m_t) is probabilistically correlated with the true memory item m_t. Noise η reduces the retrieval probability p(η), modeling imperfect recall or approximation in memory access. Lower η yields more accurate retrieval; higher η introduces more errors.</p>
            <p><strong>Critic Channel.</strong> The Critic can make two types of errors when evaluating a candidate: α = Pr(approve | incorrect) is the false approval rate—the probability of approving a wrong answer—and β = Pr(reject | correct) is the false rejection rate—the probability of rejecting a correct answer. The <em>positive predictive value</em> (PPV) of approved items is given by P(correct|approve) = (1-β)p&apos; / [(1-β)p&apos; + α(1-p&apos;)], where p&apos; is the prior probability that a candidate is correct. Minimizing α and β ensures high-quality memory; a high PPV means that when the Critic approves a candidate, we can be confident it is actually correct.</p>
            <p><strong>Critic-Gated Memory Update.</strong> Memory grows only when the Critic approves: M_&#123;t+1&#125; = M_t ∪ &#123;(q_t, a_t, metadata)&#125; if approved, or M_&#123;t+1&#125; = M_t if rejected. This mirrors spike-timing dependent plasticity (STDP) in neuroscience: only well-timed and verified events produce lasting changes in memory. Rejected candidates leave no trace, preventing incorrect results from contaminating future reasoning steps.</p>
          </div>
        </div>
      </Section>
    </main>
  );
}
